<?php

/**
 * Webrick - Middleware: Verify Signed URLs.
 *
 * Validates HMAC signatures on incoming requests generated by SignedUrlGenerator:
 * - Extracts and removes the signature query parameter.
 * - Optionally enforces expiry with configurable leeway.
 * - Reconstructs the canonical payload (path + sorted query) and verifies the HMAC.
 * - Returns an appropriate plaintext Response on failure; delegates to next on success.
 *
 * @package Infocyph\Webrick\Middleware
 */

declare(strict_types=1);

namespace Infocyph\Webrick\Middleware;

use Closure;
use Infocyph\Webrick\Constants\StatusEnum;
use Infocyph\Webrick\Request\Request;
use Infocyph\Webrick\Response\Response;
use Infocyph\Webrick\Router\Url\Signature;
use Infocyph\Webrick\Router\Url\SignedUrlGenerator;

/**
 * Middleware that verifies signed URLs and optional expirations.
 *
 * The signature is expected under the query parameter defined by
 * SignedUrlGenerator::SIG_PARAM (default "_sig"). If SignedUrlGenerator::EXPIRES_PARAM
 * (default "_exp") is present, it is checked against the current time with an optional
 * leeway. Any failure returns a plaintext Response with an appropriate status code.
 */
final readonly class VerifySignedUrlMiddleware
{
    /**
     * Configure signature verification.
     *
     * @param string $secret Secret key shared with the signer.
     * @param int|string $leeway Allowed clock skew for expiry checks (in seconds).
     */
    public function __construct(
        private string $secret,
        private int|string $leeway = 0,
    ) {
    }

    /**
     * Verify the request's signed URL and optionally its expiration.
     *
     * Steps:
     * 1) Extract and remove the signature parameter from the query.
     * 2) If an expiry parameter exists, ensure it has not passed (considering leeway).
     * 3) Canonicalize query order, reconstruct payload (path + query), and validate HMAC.
     * 4) On success, delegate to the next middleware/handler.
     *
     * @param Request $request The incoming HTTP request.
     * @param Closure $next The next handler in the middleware chain.
     *
     * @return mixed A Response on failure or the result of the next handler on success.
     */
    public function __invoke(Request $request, Closure $next)
    {
        // 1) pull query and signature, then remove _sig
        $qs = $request->getQueryParams();
        $sig = $qs[SignedUrlGenerator::SIG_PARAM] ?? '';
        if (!is_string($sig) || $sig === '') {
            return Response::plaintext('Missing signature', StatusEnum::BAD_REQUEST->value);
        }
        unset($qs[SignedUrlGenerator::SIG_PARAM]);

        // 2) expiry check (if present)
        if (isset($qs[SignedUrlGenerator::EXPIRES_PARAM])) {
            $exp = (int)$qs[SignedUrlGenerator::EXPIRES_PARAM];
            if (time() > $exp + $this->leeway) {
                return Response::plaintext('URL expired', StatusEnum::GONE->value);
            }
        }

        // 3) canonicalize EXACTLY like the generator
        ksort($qs); // same top-level sort as generator
        $path = $request->getUri()->getPath();
        if ($path === '' || $path[0] !== '/') {
            $path = '/' . ltrim($path, '/'); // ensure leading slash
        }

        $payload = $path;
        if ($qs !== []) {
            // Build canonical query string with RFC 3986 encoding (as in generator)
            $payload .= '?' . http_build_query($qs, '', '&', PHP_QUERY_RFC3986);
        }

        // 4) verify signature
        if (!Signature::check($payload, $sig, $this->secret)) {
            return Response::plaintext('Invalid signature', StatusEnum::FORBIDDEN->value);
        }

        // 5) hand off to the next middleware/controller
        return $next($request);
    }
}
