#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 |------------------------------------------------------------------
 |  Webrick CLI entry point
 |------------------------------------------------------------------
 |  Usage examples:
 |     php webrick route:cache   # compile & cache routes
 |     php webrick route:clear   # remove cache
 |     php webrick route:list    # pretty table of routes
 |
 |  Add more sub-commands in src/router/cli/ as needed.
 |------------------------------------------------------------------
*/

require __DIR__ . '/vendor/autoload.php';

use Infocyph\Webrick\Router\CLI\RouteCacheCommand;

RouteCacheCommand::main($argv);
